#!/bin/bash
set -a
source .env
set +a

docker build \
  --build-arg FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" \
  --build-arg FIREBASE_PRIVATE_KEY_ID="$FIREBASE_PRIVATE_KEY_ID" \
  --build-arg FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY" \
  --build-arg FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL" \
  --build-arg FIREBASE_CLIENT_ID="$FIREBASE_CLIENT_ID" \
  --build-arg FIREBASE_AUTH_URI="$FIREBASE_AUTH_URI" \
  --build-arg FIREBASE_TOKEN_URI="$FIREBASE_TOKEN_URI" \
  --build-arg FIREBASE_AUTH_PROVIDER_X509_CERT_URL="$FIREBASE_AUTH_PROVIDER_X509_CERT_URL" \
  --build-arg FIREBASE_CLIENT_X509_CERT_URL="$FIREBASE_CLIENT_X509_CERT_URL" \
  --build-arg FIREBASE_UNIVERSE_DOMAIN="$FIREBASE_UNIVERSE_DOMAIN" \
  --build-arg JWT_SECRET="$JWT_SECRET" \
  --build-arg JWT_REFRESH_SECRET="$JWT_REFRESH_SECRET" \
  --build-arg JWT_EXPIRES_IN="$JWT_EXPIRES_IN" \
  --build-arg JWT_REFRESH_EXPIRES_IN="$JWT_REFRESH_EXPIRES_IN" \
  -t comnyang/auth:latest .
