name: Build and Deploy Auth Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DSPM_Dashboard-Auth/**'
      - 'DSPM_Dashboard-Auth/Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./DSPM_Dashboard-Auth
          file: ./DSPM_Dashboard-Auth/Dockerfile
          push: true
          tags: comnyang/auth:latest
